baseURL = 'https://example.org/'
languageCode = 'fr-FR'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Accueil'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'DevLog'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'A propos'
    pageRef = '/a-propos'
    weight = 30
  [[menus.main]]
    name = 'Mon CV'
    pageRef = '/mon-cv'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.150.0'
